# Generated by Django 5.0 on 2023-12-25 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_contacts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
