# Generated by Django 5.0 on 2023-12-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_direct_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direct_contacts',
        ),
    ]
