# Generated by Django 5.0 on 2023-12-25 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_user_direct_contacts'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_contacts',
            field=models.ManyToManyField(related_name='contact_of', through='chat.DirectMessage', to=settings.AUTH_USER_MODEL),
        ),
    ]
