# Generated by Django 5.0 on 2023-12-06 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='id',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='message_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.message'),
            preserve_default=False,
        ),
    ]
