# Generated by Django 5.0 on 2023-12-09 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_directmessage_id_remove_groupmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='chat.message'),
        ),
    ]
